### PR TITLE
Fixed regex for management group in armUrlParser.ts

### LINKED ISSUE #772: SyntaxError: Invalid regular expression: Nothing to repeat
No matter what command I'm running, I'm getting the following error;

```
error compiler-version-mismatch: Current Cadl compiler conflicts with local version of @cadl-lang/compiler referenced in D:/Projects/RP/src/Cadl/cadl.
If this error occurs on the command line, try running `cadl` with a working directory of D:/Projects/RP/src/Cadl/cadl.
If this error occurs in the IDE, try configuring the `cadl-server` path to D:/Projects/RP/src/Cadl/cadl/node_modules/.bin/cadl-server.

Found 1 error.

C:\Users\alexbat\AppData\Local\npm-cache\_npx\7bde8d961d95e490\node_modules\oav\dist\lib\apiScenario\armUrlParser.js:66
            const managementGroupMatch = /^\/providers\/Microsoft\.Management\/managementGroups\/(?<mgmtGroupName>[^\/]+*)/gi.exec(path);
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /^\/providers\/Microsoft\.Management\/managementGroups\/(?<mgmtGroupName>[^\/]+*)/: Nothing to repeat
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\alexbat.REDMOND\AppData\Local\npm-cache\_npx\7bde8d961d95e490\node_modules\oav\dist\lib\apiScenario\gen\testScenarioGenerator.js:41:24)
```

Environment:

```
Node: 17.8.0
oav: 2.11.9
```

### PR DESCRIPTION
**Pull request by abatishchev**
Fixes #772.

I'm new to oav and to JS/TS/Node so please don't shoot :) Let me know if this fix makes any sense.

Tested it here: https://rubular.com/r/I78hVC8xKxZgJQ
And here: https://jsfiddle.net/Lxkost0d/1/

### CODE REVIEW

File: lib/apiScenario/armUrlParser.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export class ArmUrlParser {
   } {
     if (scopeSlice.length === 0) {
       const managementGroupMatch =
-        /^\/providers\/Microsoft\.Management\/managementGroups\/(?<mgmtGroupName>[^\/]+*)/gi.exec(
+        /^\/providers\/Microsoft\.Management\/managementGroups\/(?<mgmtGroupName>[^\/].+)/gi.exec(
```
Comment (leniatgh) [inline lib/apiScenario/armUrlParser.ts]:
```suggestion
        /^\/providers\/Microsoft\.Management\/managementGroups\/(?<mgmtGroupName>[^\/]+)/gi.exec(
```

**Review by leniatgh — APPROVED** [review]
