### PR TITLE
Remove unused dependency `z-schema`

### LINKED ISSUE #1096: remove dependency z-schema
- remove dependency `z-schema` from `package.json`
- run `npm install` to update `package-lock.json`
- remove any code using z-schema
- run tests to ensure no regressions

### PR DESCRIPTION
**Pull request by mikeharder**
- fixes #1096
- added in #306
- in #317, caller was removed, but properties were (accidentally?) left behind

### CODE REVIEW

File: lib/util/validationError.ts [hunk 1]
```diff
@@ -178,9 +177,6 @@ export interface NodeError<T extends NodeError<T>> {
   jsonUrl?: string;
 
   directives?: StringMap<unknown>;
-
-  readonly [jsonSymbol]?: JsonRef;
```
Comment (mikeharder) [inline lib/util/validationError.ts:182]: calling code was removed in #317, so should be safe to delete these properties

**Review by scbedd — APPROVED** [review]
