### PR TITLE
[HTML Report] Fix display issues in Windows OS

### LINKED ISSUE #1007: [HTML Report]  Details of Failed Operations cannot be displayed in Windows.
## Description
After running **oav validate-traffic** in Windows OS, the details of **Failed Operations** does not show in the generated .html report.

## Expected

image

## Actual

image

### LINKED ISSUE #1008: [HTML Report] Links of schemaPath and payloadFilePath do not point to the correct file location
## Description

When running **oav validate-traffic** in local device, the links of **schemaPath** and **payloadFilePath** in the generated .html report do not point to the correct file location.

image

### PR DESCRIPTION
**Pull request by ms-zhenhua**
## Changes

1. Fix https://github.com/Azure/oav/issues/1007
2. Fix https://github.com/Azure/oav/issues/1008

### CODE REVIEW

File: lib/report/generateReport.ts [hunk 1]
```diff
@@ -224,7 +215,9 @@ export class CoverageView {
 
       this.resultsForRendering = this.coverageResultsForRendering.map((item) => {
         const data = this.validationResultsForRendering.find(
-          (i) => i.specFilePath && item.spec.includes(i.specFilePath)
+          (i) =>
+            i.specFilePath &&
+            item.spec.split(path.win32.sep).join(path.posix.sep).includes(i.specFilePath)
```
Comment (scbedd) [inline lib/report/generateReport.ts:220]: I see what you're doin here. This is a creative solution to always forcing linux style!

**Review by scbedd — APPROVED** [review]
Thanks @ms-zhenhua ! I consider this to be a bugfix. Please bump the version of `oav` by 1 patch version and update the changelog.md to reflect the change as well!

**Comment by ms-zhenhua** [comment]
Hey @scbedd, thank you for your review. I have updated the minor version and changelog. Kindly take another view. Thanks.
